image: docker:latest
services:
  - docker:dind

step-test:
  stage: test
  only:
    - development
  tags:
    - development
  script:
    - apk add py-pip==7.1.2-r0
    - pip install docker-compose==1.28.6
    - docker image prune -f
    - docker-compose --profile test up --abort-on-container-exit
