image: tiangolo/docker-with-compose

step-test:
  stage: test
  only:
    - development
  tags:
    - development
  script:
    - docker image prune -f
    - docker-compose --profile test up --abort-on-container-exit
