image: docker:latest
services:
  - docker:dind

step-test:
  stage: test
  only:
    - development
  tags:
    - development
  script:
    - apk add "py3-pip>20"
    - pip3 install "docker-compose>=1.25"
    - docker image prune -f
    - docker-compose --profile test up --abort-on-container-exit
