image: docker:latest
services:
  - docker:dind

step-test:
  stage: test
  only:
    - development
  tags:
    - development
  script:
    - apk add --update py3-pip
    - pip3 install docker-compose
    - docker image prune -f
    - docker-compose --profile test up --abort-on-container-exit
