version: "2"
services:
  app:
    build: .
    command: npm start
    profiles:
      - build
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      DOCKERBUILD: docker

  postgres:
    image: postgres
    profiles:
      - build
    volumes:
      - ./postgres/socialmedia.sql:/docker-entrypoint-initdb.d/socialmedia.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - test
    depends_on:
      - test-postgres
    command: npm test
    environment:
      DOCKERBUILD: docker

  test-postgres:
    image: postgres
    volumes:
      - ./postgres/socialmedia.sql:/docker-entrypoint-initdb.d/socialmedia.sql
    profiles:
      - test
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
