version: "2"
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      DOCKERBUILD: true

  postgres:
    image: postgres
    volumes:
      - ./postgres/socialmedia.sql:/docker-entrypoint-initdb.d/socialmedia.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - app
      - test-postgres
    command: npm test
    DOCKERBUILD: true

  test-postgres:
    image: postgres
    volumes:
      - ./postgres/socialmedia.sql:/docker-entrypoint-initdb.d/socialmedia.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
