const router = require("express").Router(),
  createComment = require("../controller/comments/createComment"),
  getComments = require("../controller/comments/getComments"),
  removeComment = require("../controller/comments/removeComments"),
  verify = require("../controller/userAuth/verify");
router.post("/createComment", verify, createComment, async (req, res) => {});
router.post("/getComments", verify, getComments, async (req, res) => {});
router.put("/removeComment", verify, removeComment, async (req, res) => {});
module.exports = router;
